### PR TITLE
Icon request: standard device icons

### LINKED ISSUE #80: Icon request: standard device icons
I'd like to cover all [standard device icons](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#devices) in the firmware updater. Some icons are still missing or follow a different naming scheme. Currently we're still [manually mapping](https://github.com/canonical/firmware-updater/blob/f1934c6f56c8ee7d6480d8ed4a5b61f0168be2e2/lib/src/widgets/device_icon.dart#L4) the standard icon names to appropriate Yaru icons if they differ. Would it be possible to rename some existing icons or provide alternative names for the same icon?

- audio-card (-> audio, should have a dedicated icon imo)
- ~~audio-input-microphone (-> microphone)~~
- ~~battery (-> battery_level_100)~~
- [camera_web](https://github.com/canonical/firmware-updater/issues/125) (missing)
- modem (missing but probably irrelevant in 2022 :D)
- ~~pda (-> smartphone)~~
- scanner (missing)
- ~~video-display (-> desktop_display)~~

### PR DESCRIPTION
**Pull request by Jupi007**
**audio-card**

Same as [yaru](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/scalable/devices/audio-card-symbolic.svg).

Capture d’écran du 2022-11-17 11-02-40

**modem**

Same as [yaru](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/scalable/devices/modem-symbolic.svg).

Capture d’écran du 2022-11-17 10-53-58

**scanner**

Same as [yaru](https://github.com/ubuntu/yaru/blob/master/icons/Yaru/scalable/apps/scanner-symbolic.svg).

Capture d’écran du 2022-11-17 10-45-57

**camera-web**

Mix between, [camera-photo](https://github.com/ubuntu/yaru_icons.dart/blob/master/icons/camera/photo.svg) and [folder-remote](https://github.com/ubuntu/yaru_icons.dart/blob/master/icons/folder/remote.svg).

Capture d’écran du 2022-11-17 10-34-06

@d-loose I suppose that a `camera-web` is a camera on the web, it is ok?

Fixes #80

### CODE REVIEW

**Comment by d-loose** [comment]
@Jupi007 great work, thanks a lot!
I guess `camera-web` simply means 'webcam' and historically refers to external cameras that could be clipped to your monitor, or placed on top of it in the old CRT times (I'm sure everyone had [one of those](https://en.wikipedia.org/wiki/QuickCam#/media/File:Logitech_QuickCam_Express_-8477.jpg) back then). In fact the corresponding GNOME icon looks like one of those:

gnome-camera-web
But I'm perfectly happy with your icon! Maybe someone with a better UI/UX background has thoughts on this?

For the audio card, I'd expect something closer to [this](https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/devices/audio-card-symbolic.svg), but we should stick to the existing Yaru icons here (and maybe change some of them there if necessary).

**Comment by madsrh** [comment]
I had the same thought as @d-loose  :D image

**Comment by Feichtmeier** [comment]
Wow 😲😳 am I really the only one with an external Webcam?!?

**Comment by Jupi007** [comment]
I am stupid, web-camera mean a webcam 🤦‍♂️
I was thinking of a kind of camera on the network 😅

I pretty much like your webcam design @madsrh 👍

> Wow astonishedflushed am I really the only one with an external Webcam?!?

Nono, you're not alone, I bought one for the ubuntu live :p

> For the audio card, I'd expect something closer to [this](https://github.com/GNOME/adwaita-icon-theme/blob/master/Adwaita/scalable/devices/audio-card-symbolic.svg), but we should stick to the existing Yaru icons here (and maybe change some of them there if necessary).

I was first planning to do that kind of design.
But I think we should create a real device card icon here, and update the original yaru one.

**Comment by Jupi007** [comment]
Let me know what you think of this:

Capture d’écran du 2022-11-17 16-50-38
Capture d’écran du 2022-11-17 16-50-24

**Comment by d-loose** [comment]
Those look really good!

**Comment by Jupi007** [comment]
Perfect, merging so :D
Thanks everybody for your feedback!

**Pull request merged**
