### PR TITLE
feat: refresh example app

### LINKED ISSUE #140: Refresh example app
The example app could be improved in various way, and it is also badly designed in term of code architecture.

### PR DESCRIPTION
**Pull request by Jupi007**
- Use `handy_window`;
- Use `YaruWindowTitleBar`;
- Fix search input focus issue;
- Various refactoring.

Capture d’écran du 2023-08-01 12-39-08

Fixes #140 #134

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Neat!

**Comment by Feichtmeier** [comment]
I wonder why it does not deploy to the github page 🤔

**Comment by Jupi007** [comment]
> I wonder why it does not deploy to the github page thinking

Yeah, I looked a little bit but I can't find the reason... weird.

**Comment by Feichtmeier** [comment]
ah I think because the github action is set to master

**Comment by Jupi007** [comment]
Indeed, nice catch :D

**Pull request merged**
