### PR TITLE
Add source code </> icon

### LINKED ISSUE #78: Icon request: source code </>
Not super important yet nice addition to the yaru widgets example:)

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2022-11-12 18-26-59
Capture d’écran du 2022-11-12 18-18-38

Fixes #78

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Thanks @Jupi007 !

Somehow my eyes always move from one edge to the other 😂
Let @madsrh also have a look

**Comment by Feichtmeier** [comment]
grafik
grafik
grafik
some icons I found on google

and the pan_XXX icons of yaru looks like they have a different angle ?
grafik

**Comment by madsrh** [comment]
TBH I think the PR is fine. I had the thought that it could use a bit more space, since it almost looks like the line is overlapping - but it isn't.

image


> and the pan_XXX icons of yaru looks like they have a different angle ?

🤔  Or like in the Terminal, we could have a look at Ubuntu mono font which is slightly different
Skærmbillede 2022-11-12 kl  21 30 29

Skærmbillede 2022-11-12 kl  22 02 20

I don't have a strong opinion here, but would something like this be possible and still get a sharp icon @Jupi007 ?

**Comment by Feichtmeier** [comment]
what if the / would not be higher than < and > ?

**Comment by Jupi007** [comment]
@Feichtmeier @madsrh Thanks for your feedback :)

The first iteration was done too quickly :D
I think that the `/` was too height, and the angle of `<>` too large.
This version is better from my point of view:

image

Capture d’écran du 2022-11-12 23-10-43


@Feichtmeier Imo the vertical bar doesn't look good when it is the same height as the chevrons.
I personally think it doesn't look like a real </>

image

@madsrh Wdyt?

**Comment by madsrh** [comment]
> I personally think it doesn't look like a real </>

+1

I like the "better icon" you just pushed.

@Feichtmeier ?

**Comment by Feichtmeier** [comment]
looks good! +1

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
