### PR TITLE
add keyboard-shortcuts-icons

### PR DESCRIPTION
**Pull request by Muqtxdir**
@Jupi007 does this look okay?

### CODE REVIEW

**Review by Jupi007 — CHANGES_REQUESTED** [review]
Thanks a lot for your contribution @Muqtxdir :)

I have a few notes:

- there is really a lot of points, I think you should redraw the shapes, then convert them with `stroke to path` ;
- I think the icon could looks better like this: Capture d’écran du 2021-12-19 19-24-26
- due to the usage of an icon font, we can't play with half transparent path. But if you want, you can use .5px stroke on the top-left square of the non-filled icon (but make it normal on the filled one) so it looks like if it was half transparent  ;
- when you are Ok with your changes, you must run the `build-icons.sh` script to generate the font and update the dart class, follow instructions in the README ;
- finally, you should update the `_to` const in `example/lib/main.dart` line `33` according to the last code point in `lib/src/yaru_icons.dart`.

Thanks :)

**Comment by Muqtxdir** [comment]
@Jupi007 i reduced the no. of points to less but since im on fedora, snap-apps like `flutter` are not playing well. so i could not install `fantasticon_flutter`. could you please build/render these changes as font in this PR? (_also modify anything if it seems necessary_)

**Comment by Jupi007** [comment]
@Muqtxdir I rendered the icons. I also make a little modification to the top left key (.5px stroke).

Capture d’écran du 2021-12-21 16-28-58
Capture d’écran du 2021-12-21 16-44-32

**Comment by Muqtxdir** [comment]
Thanks @Jupi007, you're the best!

**Pull request merged**
