### PR TITLE
Create placeholder icon

### LINKED ISSUE #118: Placeholder icon/Origami decoration?
In the software store I fiddled around with containers and rotate to create a 
fallback/placeholder icon based on the one from snapcraft
grafik
[missing icon icon](https://assets.ubuntu.com/v1/be6eb412-snapcraft-missing-icon.svg) 
Result is quiet okay but very constrained in the app icon
grafik

@Jupi007 do you have a smart idea how we could create a placeholder icon that looks similar to this but just adapts to the parent container and extens itself to all borders? Then we could also use this in more places, or as soft background decoration to create more "origami"/3d looks

### PR DESCRIPTION
**Pull request by Jupi007**
| Light | Dark |
| --- | --- |
| Capture d’écran du 2023-01-21 21-05-07 | Capture d’écran du 2023-01-21 21-04-59 |

**Note:** I really need to clean up the example app.

CC @Zoospora @anasereijo

Fixes #118

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Really 👍 🙂 nice

**Comment by Jupi007** [comment]
Thanks :)

I just wait for @Zoospora @anasereijo approval before merging.

**Comment by Zoospora** [comment]
It looks great! Nice work 😊
It's perfect for me. 

Thanks again!

**Comment by Feichtmeier** [comment]
@Jupi007 could you make a new release and include it in yaru_widgets? so I don't get a version conflict when updating software

**Comment by Jupi007** [comment]
Ofc :)
In fact, I have some pending changes I wanted to finish and push tomorrow.

Do you want a new release this night?

**Pull request merged**
