### PR TITLE
Example: update deps

### PR DESCRIPTION
**Pull request by Jupi007**
- update yaru dependencies ;
- fix flutter depreciations.

Capture d’écran du 2023-02-09 20-07-12

### CODE REVIEW

**Comment by Feichtmeier** [comment]
eventually you need to take care of the searchbar now

**Comment by Jupi007** [comment]
Oh indeed 😅

image

**Comment by Jupi007** [comment]
I'll finish this tomorrow :)
Not have enough time this night.

**Comment by Jupi007** [comment]
Capture d’écran du 2023-02-17 10-58-58
image

Quick fix for the search entry.
I'd like to redo the example from scratch, so more improvements will coming :)

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
