### PR TITLE
Add several new icons

### LINKED ISSUE #69: IconRequest: several software category icons
I could use some more icons to help with the packagekit groups. Also the communication icon I used (subtiles) never perfectly fitted :)

"Missing" icons:

-    gnome
 -   kde
  -  xfce
  -  collections
   - repos
   - communication
   - legacy
   - office
   - documentation

grafik

### PR DESCRIPTION
**Pull request by Jupi007**
- [x]     gnome:

Capture d’écran du 2022-10-24 23-55-04

- [x]     kde:

Capture d’écran du 2022-10-24 23-55-28

- [x]     xfce:

image

- [x]     communication:

Capture d’écran du 2022-10-24 23-56-50
Capture d’écran du 2022-10-24 23-57-05

- [x]     legacy (I'm not sure of this one):

Capture d’écran du 2022-10-24 23-54-28

- [x]     office:

Capture d’écran du 2022-10-24 23-56-05

- [ ]     documentation: maybe use the `question` icon?
- [ ]     collections: can you give me a bit more context?
- [ ]     repos: same question as `collections`.

@Feichtmeier 

Closes #69

### CODE REVIEW

**Comment by madsrh** [comment]
Great work @Jupi007 💪 
The ~~microwave oven~~ legacy computer looks a bit odd IMHO. What about something like this (not aligned to any grid here):
image

**Comment by Jupi007** [comment]
@madsrh Like this?

Capture d’écran du 2022-10-25 17-26-25

Capture d’écran du 2022-10-25 17-27-43

**Comment by Feichtmeier** [comment]
packagekit groups are weird

 collections: "A collection is a metapackage that can represent a group, where the package mapping is done inside the backend. It is not like a [catalog](http://www.packagekit.org/pk-faq.html#catalogs) where an external file provides a meta-group. This enables the “group install” and “group remove” functionality people have been requesting since version 0.1.0, without get another abstract group mapping or extra API to support."

🤷 

repos: no idea either, eventually a packagekit ID can also be a repo?

Sorry for this small infos but those distributor logos are already nice 👍 I guess I can make the rest out of other icons
Eventually I need to merge both snap sections (much cleaner API) with packagekit groups, since they want software to show merged results

**Comment by Jupi007** [comment]
I don't know if I understood correctly (sound very abstract), but what about use the `package` icon for both **collections** and **repos**?

**Comment by Feichtmeier** [comment]
> I don't know if I understood correctly (sound very abstract), but what about use the `package` icon for both **collections** and **repos**?

good idea  =)

**Comment by Feichtmeier** [comment]
for communication, maybe a chat bubble is better? somehow like subtitles but without this little subtitle text ?

**Comment by Jupi007** [comment]
Capture d’écran du 2022-10-25 18-20-29

**Comment by Feichtmeier** [comment]
Perfect thank you :)

**Comment by Jupi007** [comment]
Okay for merging?
Btw do you want a new release?

**Comment by madsrh** [comment]
> @madsrh Like this?
> 
> Capture d’écran du 2022-10-25 17-26-25
> 
> Capture d’écran du 2022-10-25 17-27-43

I like it 👍😄

**Pull request merged**
