### PR TITLE
Add many snap store related icons

### LINKED ISSUE #43: Icon request: snap, debian and flatpak
It would be lovely if we could have snap, debian and flatpak symbolics inside yaru_icons.dart

I could use it for the software project :)
grafik

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2022-05-16 23-43-48

Closes #43, #44, #45

### CODE REVIEW

**Review by Feichtmeier — APPROVED** [review]
Thank you so much!

**Comment by Jupi007** [comment]
Yw :)

Do you need a new release?

**Comment by Feichtmeier** [comment]
Currently I'm using the git version so you can wait if you want

**Comment by Jupi007** [comment]
I don't plan to add more icon for now, so I think I'll push a new release.

**Pull request merged**
