### PR TITLE
chore: release as 2.0.0

### PR DESCRIPTION
**Pull request by jpnurmi**
_Originally posted by @Jupi007 in https://github.com/ubuntu/yaru_icons.dart/issues/153#issuecomment-1619654078_

> We should make a major version bump because the animated icons API changed a lot.
I just need to make a few more changes before the release.

https://github.com/googleapis/release-please#how-do-i-change-the-version-number

Release-As: 2.0.0

### CODE REVIEW

**Comment by jpnurmi** [comment]
I've never done it like this before so I hope it works... I have previously forced it through the CI but I just missing the reusable release action is missing input for that.

**Review by Jupi007 — APPROVED** [review]
LGTM 👍

So we can make empty PR?
Another thing I didn't know 😅
How did you do?

**Comment by jpnurmi** [comment]
`git commit --allow-empty` :slightly_smiling_face:

**Comment by Jupi007** [comment]
Ooooh, okay. Thanks 🙂

**Pull request merged**
