### PR TITLE
Release version 1.0.3

### PR DESCRIPTION
**Pull request by Jupi007**

### CODE REVIEW

**Comment by Feichtmeier** [comment]
damn I am too slow :D got an update to your example

**Review by Feichtmeier — APPROVED** [review]

**Comment by Jupi007** [comment]
> damn I am too slow :D got an update to your example

Is it to update yaru deps?

**Comment by Feichtmeier** [comment]
yes! cool :) Then I can close vscode :)

**Comment by Feichtmeier** [comment]
@Jupi007 could you upload to pub?

**Pull request merged**
