### PR TITLE
feat: rework some icons

### PR DESCRIPTION
**Pull request by Jupi007**
Capture d’écran du 2023-11-21 21-08-42

_Note that it will require to update the related icons in the yaru repository._

@madsrh @Muqtxdir @Feichtmeier  If you have any comment or suggestion :)

@d-loose @anasereijo I added a filled version of the `wrench` icon, so you can use outlined icons (and eventually filled when selected) in the app-store sidebar.

### CODE REVIEW

**Comment by madsrh** [comment]
These look great @Jupi007 👌

**Review by Muqtxdir — APPROVED** [review]
I like the new look 👍

**Comment by Feichtmeier** [comment]
Looks very good! Great work

**Comment by Jupi007** [comment]
Great!
Thanks for your feedback guys 😀

**Comment by d-loose** [comment]
Very nice, thanks a lot!

**Comment by anasereijo** [comment]
nice icons!!! Will create an issue to update the wrench icon! thank you

**Comment by Jupi007** [comment]
@anasereijo Okay, thank you.
I will push a release so you can use it.

**Pull request merged**
